package com.kyvora.backend.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Map;

@Service
@Slf4j
public class AiGatewayService {
    private final HttpClient httpClient;
    private final ObjectMapper objectMapper;

    @Value("${kyvora.ai.gemini.api-key:}")
    private String geminiApiKey;

    @Value("${kyvora.ai.openrouter.api-key:}")
    private String openrouterApiKey;

    @Value("${kyvora.ai.groq.api-key:}")
    private String groqApiKey;

    @Value("${kyvora.ai.huggingface.api-key:}")
    private String huggingfaceApiKey;

    @Value("${kyvora.ai.sambanova.api-key:}")
    private String sambanovaApiKey;

    public AiGatewayService(ObjectMapper objectMapper) {
        this.httpClient = HttpClient.newHttpClient();
        this.objectMapper = objectMapper;
    }

    public String callAi(String provider, String model, String prompt) throws Exception {
        log.info("AI call requested. Provider: {}, Model: {}", provider, model);

        return switch (provider.toLowerCase()) {
            case "gemini" -> callGemini(model, prompt);
            case "groq" -> callGroq(model, prompt);
            case "openrouter" -> callOpenRouter(model, prompt);
            default -> throw new IllegalArgumentException("Unsupported AI provider: " + provider);
        };
    }

    private String callGemini(String model, String prompt) throws Exception {
        if (geminiApiKey.isEmpty()) {
            throw new IllegalStateException("Gemini API key is not configured");
        }
        
        String actualModel = (model == null || model.isEmpty()) ? "gemini-1.5-pro" : model;
        String url = "https://generativelanguage.googleapis.com/v1beta/models/" + actualModel + ":generateContent?key=" + geminiApiKey;

        Map<String, Object> requestBody = Map.of(
                "contents", List.of(
                        Map.of("parts", List.of(
                                Map.of("text", prompt)
                        ))
                )
        );

        String jsonPayload = objectMapper.writeValueAsString(requestBody);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                .build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Gemini API call failed with status: " + response.statusCode() + " details: " + response.body());
        }

        Map<?, ?> responseMap = objectMapper.readValue(response.body(), Map.class);
        List<?> candidates = (List<?>) responseMap.get("candidates");
        if (candidates != null && !candidates.isEmpty()) {
            Map<?, ?> firstCandidate = (Map<?, ?>) candidates.getFirst();
            Map<?, ?> content = (Map<?, ?>) firstCandidate.get("content");
            List<?> parts = (List<?>) content.get("parts");
            if (parts != null && !parts.isEmpty()) {
                Map<?, ?> firstPart = (Map<?, ?>) parts.getFirst();
                return (String) firstPart.get("text");
            }
        }
        return "No text response generated by Gemini.";
    }

    private String callGroq(String model, String prompt) throws Exception {
        if (groqApiKey.isEmpty()) {
            throw new IllegalStateException("Groq API key is not configured");
        }

        String actualModel = (model == null || model.isEmpty()) ? "mixtral-8x7b-32768" : model;
        String url = "https://api.groq.com/openai/v1/chat/completions";

        Map<String, Object> requestBody = Map.of(
                "model", actualModel,
                "messages", List.of(
                        Map.of("role", "user", "content", prompt)
                )
        );

        String jsonPayload = objectMapper.writeValueAsString(requestBody);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer " + groqApiKey)
                .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                .build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("Groq API call failed with status: " + response.statusCode() + " details: " + response.body());
        }

        Map<?, ?> responseMap = objectMapper.readValue(response.body(), Map.class);
        List<?> choices = (List<?>) responseMap.get("choices");
        if (choices != null && !choices.isEmpty()) {
            Map<?, ?> firstChoice = (Map<?, ?>) choices.getFirst();
            Map<?, ?> message = (Map<?, ?>) firstChoice.get("message");
            return (String) message.get("content");
        }
        return "No text response generated by Groq.";
    }

    private String callOpenRouter(String model, String prompt) throws Exception {
        if (openrouterApiKey.isEmpty()) {
            throw new IllegalStateException("OpenRouter API key is not configured");
        }

        String actualModel = (model == null || model.isEmpty()) ? "google/gemini-2.5-pro" : model;
        String url = "https://openrouter.ai/api/v1/chat/completions";

        Map<String, Object> requestBody = Map.of(
                "model", actualModel,
                "messages", List.of(
                        Map.of("role", "user", "content", prompt)
                )
        );

        String jsonPayload = objectMapper.writeValueAsString(requestBody);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer " + openrouterApiKey)
                .header("HTTP-Referer", "https://kyvora.io")
                .header("X-Title", "Kyvora Studio")
                .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                .build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("OpenRouter API call failed with status: " + response.statusCode() + " details: " + response.body());
        }

        Map<?, ?> responseMap = objectMapper.readValue(response.body(), Map.class);
        List<?> choices = (List<?>) responseMap.get("choices");
        if (choices != null && !choices.isEmpty()) {
            Map<?, ?> firstChoice = (Map<?, ?>) choices.getFirst();
            Map<?, ?> message = (Map<?, ?>) firstChoice.get("message");
            return (String) message.get("content");
        }
        return "No text response generated by OpenRouter.";
    }
}
